name: Daily Malaimurasu PDF Download

on:
  schedule:
    - cron: '30 21 * * *'  # Runs at 3:00 AM IST
  workflow_dispatch:       # Allows manual trigger

jobs:
  download-epaper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python run.py

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: malaimurasu-pdfs
          path: '*.pdf'
